### ISSUE TITLE
[Unexpected Behavior] Mathjax3 could not be apply by Markdown-it

### ISSUE THREAD

**Issue by Dragon1573** [tani/markdown-it-mathjax3#54]
@tani, the latest version of `markdown-it-mathjax3@3.0.0` encounter another question. The full operation details are listed below.

<details>
<summary>Current environment before upgrade</summary>

```text
C:\Users\Dragon1573\Repos\Study-Notes>node --version
v16.13.1

C:\Users\Dragon1573\Repos\Study-Notes>npm --version
8.1.2

C:\Users\Dragon1573\Repos\Study-Notes>yarn --version
3.1.0

C:\Users\Dragon1573\Repos\Study-Notes>yarn info
├─ dayjs@npm:1.10.7
│  └─ Version: 1.10.7
│
├─ inquirer@npm:8.2.0
│  ├─ Version: 8.2.0
│  │
│  └─ Dependencies
│     ├─ ansi-escapes@npm:^4.2.1 → npm:4.3.2   
│     ├─ chalk@npm:^4.1.1 → npm:4.1.2
│     ├─ cli-cursor@npm:^3.1.0 → npm:3.1.0     
│     ├─ cli-width@npm:^3.0.0 → npm:3.0.0      
│     ├─ external-editor@npm:^3.0.3 → npm:3.1.0
│     ├─ figures@npm:^3.0.0 → npm:3.2.0        
│     ├─ lodash@npm:^4.17.21 → npm:4.17.21     
│     ├─ mute-stream@npm:0.0.8 → npm:0.0.8     
│     ├─ ora@npm:^5.4.1 → npm:5.4.1
│     ├─ run-async@npm:^2.4.0 → npm:2.4.1      
│     ├─ rxjs@npm:^7.2.0 → npm:7.4.0
│     ├─ string-width@npm:^4.1.0 → npm:4.2.2   
│     ├─ strip-ansi@npm:^6.0.0 → npm:6.0.0     
│     └─ through@npm:^2.3.6 → npm:2.3.8        
│
├─ json2yaml@npm:1.1.0
│  ├─ Version: 1.1.0
│  │
│  ├─ Exported Binaries
│  │  ├─ json2yaml
│  │  ├─ json2yml
│  │  ├─ jsontoyaml
│  │  └─ jsontoyml
│  │
│  └─ Dependencies
│     └─ remedial@npm:1.x → npm:1.0.8
│
├─ markdown-it-footnote@npm:3.0.3
│  └─ Version: 3.0.3
│
├─ markdown-it-mathjax3@npm:3.0.0-0
│  ├─ Version: 3.0.0-0
│  │
│  └─ Dependencies
│     ├─ juice@npm:^8.0.0 → npm:8.0.0
│     └─ mathjax-full@npm:^3.2.0 → npm:3.2.0
│
├─ rimraf@npm:3.0.2
│  ├─ Version: 3.0.2
│  │
│  ├─ Exported Binaries
│  │  └─ rimraf
│  │
│  └─ Dependencies
│     └─ glob@npm:^7.1.3 → npm:7.1.7
│
├─ study-notes@workspace:.
│  ├─ Version: 1.0.0
│  │
│  └─ Dependencies
│     ├─ dayjs@npm:^1.10.7 → npm:1.10.7
│     ├─ inquirer@npm:^8.2.0 → npm:8.2.0
│     ├─ json2yaml@npm:^1.1.0 → npm:1.1.0
│     ├─ markdown-it-footnote@npm:^3.0.3 → npm:3.0.3
│     ├─ markdown-it-mathjax3@npm:^3.0.0-0 → npm:3.0.0-0
│     ├─ rimraf@npm:^3.0.2 → npm:3.0.2
│     ├─ vuepress-plugin-one-click-copy@npm:^1.0.6 → npm:1.0.6
│     ├─ vuepress-plugin-zooming@npm:^1.1.8 → npm:1.1.8
│     ├─ vuepress-theme-vdoing@npm:^1.8.6 → npm:1.8.6
│     ├─ vuepress@npm:^1.8.3 → npm:1.8.3
│     ├─ yamljs@npm:^0.3.0 → npm:0.3.0
│     └─ vuepress-plugin-sitemap@npm:^2.3.1 → npm:2.3.1 [cb833]
│
├─ vuepress-plugin-one-click-copy@npm:1.0.6
│  └─ Version: 1.0.6
│
├─ vuepress-plugin-sitemap@npm:2.3.1
│  ├─ Instances: 1
│  ├─ Version: 2.3.1
│  │
│  ├─ Exported Binaries
│  │  └─ vuepress-sitemap
│  │
│  └─ Dependencies
│     └─ sitemap@npm:^3.0.0 → npm:3.2.2
│
├─ vuepress-plugin-zooming@npm:1.1.8
│  ├─ Version: 1.1.8
│  │
│  └─ Dependencies
│     └─ zooming@npm:^2.1.1 → npm:2.1.1
│
├─ vuepress-theme-vdoing@npm:1.8.6
│  ├─ Version: 1.8.6
│  │
│  └─ Dependencies
│     ├─ @better-scroll/core@npm:^2.0.0-beta.6 → npm:2.4.2
│     ├─ @better-scroll/slide@npm:^2.0.0-beta.6 → npm:2.4.2
│     ├─ @vuepress/plugin-active-header-links@npm:^1.2.0 → npm:1.8.2
│     ├─ @vuepress/plugin-nprogress@npm:^1.2.0 → npm:1.8.2
│     ├─ @vuepress/plugin-search@npm:^1.2.0 → npm:1.8.2
│     ├─ chalk@npm:^4.0.0 → npm:4.1.2
│     ├─ docsearch.js@npm:^2.5.2 → npm:2.6.3
│     ├─ good-storage@npm:^1.1.1 → npm:1.1.1
│     ├─ js-yaml@npm:^3.13.1 → npm:3.14.1
│     ├─ json2yaml@npm:^1.1.0 → npm:1.1.0
│     ├─ lodash@npm:^4.17.15 → npm:4.17.21
│     ├─ stylus@npm:^0.54.5 → npm:0.54.8
│     ├─ vuepress-plugin-container@npm:^2.0.2 → npm:2.1.5
│     ├─ vuepress-plugin-smooth-scroll@npm:^0.0.3 → npm:0.0.3
│     └─ stylus-loader@npm:^3.0.2 → npm:3.0.2 [dd36c]
│
├─ vuepress@npm:1.8.3
│  ├─ Version: 1.8.3
│  │
│  ├─ Exported Binaries
│  │  └─ vuepress
│  │
│  └─ Dependencies
│     ├─ @vuepress/core@npm:1.8.3 → npm:1.8.3
│     ├─ @vuepress/theme-default@npm:1.8.3 → npm:1.8.3
│     ├─ cac@npm:^6.5.6 → npm:6.7.3
│     ├─ envinfo@npm:^7.2.0 → npm:7.8.1
│     ├─ opencollective-postinstall@npm:^2.0.2 → npm:2.0.3
│     └─ update-notifier@npm:^4.0.0 → npm:4.1.3
│
└─ yamljs@npm:0.3.0
   ├─ Version: 0.3.0
   │
   ├─ Exported Binaries
   │  ├─ json2yaml
   │  └─ yaml2json
   │
   └─ Dependencies
      ├─ argparse@npm:^1.0.7 → npm:1.0.10
      └─ glob@npm:^7.0.5 → npm:7.1.7
```

</details>
<details>
<summary>Upgrade the package interactively</summary>

```text
C:\Users\Dragon1573\Repos\Study-Notes>yarn upgrade-interactive
 Press <up>/<down> to select packages.            Press <enter> to install.
 Press <left>/<right> to select versions.         Press <ctrl+c> to abort.

? Pick the packages you want to upgrade.          Current          Range            Latest

 > markdown-it-mathjax3 ------------------------ ◯ ^3.0.0-0 ----- ◉ ^3.0.0 -------
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @vue/babel-plugin-jsx@npm:1.0.7 doesn't provide @babel/core (pa6c52), requested by @babel/plugin-syntax-jsx
➤ YN0002: │ @vuepress/core@npm:1.8.3 doesn't provide @vue/compiler-sfc (pdf33a), requested by vue-loader
➤ YN0002: │ study-notes@workspace:. doesn't provide chalk (p75ef5), requested by vuepress-plugin-sitemap
➤ YN0002: │ study-notes@workspace:. doesn't provide commander (p17913), requested by vuepress-plugin-sitemap
➤ YN0002: │ study-notes@workspace:. doesn't provide esm (p844b2), requested by vuepress-plugin-sitemap
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1m 8s
➤ YN0000: ┌ Fetch step
➤ YN0019: │ parse5-htmlparser2-tree-adapter-npm-6.0.1-60b4888f75-1848378b35.zip appears to be unused - removing
➤ YN0019: │ slick-npm-1.12.2-a4c282c110-02b586dac1.zip appears to be unused - removing
➤ YN0019: │ tslib-npm-2.3.1-0e21e18015-de17a98d46.zip appears to be unused - removing
➤ YN0019: │ valid-data-url-npm-3.0.1-d31c986fd6-06584294fb.zip appears to be unused - removing
➤ YN0019: │ web-resource-inliner-npm-5.0.0-96bf94e286-5b8a398dec.zip appears to be unused - removing
➤ YN0000: └ Completed in 1s 820ms
➤ YN0000: ┌ Link step
➤ YN0076: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 The win32-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The win32-x64 architecture is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 2s 793ms
➤ YN0000: Done with warnings in 1m 13s
```

</details>
<details>
<summary>Unexpected behavior when <code>yarn dev</code></summary>

```text
C:\Users\Dragon1573\Repos\Study-Notes>yarn dev
wait Extracting site metadata...
warning: 该文件 "C:\Users\Dragon1573\Repos\Study-Notes\docs\01.机器学习\01.蓝桥云课\assets" 序号出错，请填写正确的序号
warning: 该文件 "C:\Users\Dragon1573\Repos\Study-Notes\docs\02.数据可视化\01.Plotly\01.基础图表\assets" 序号出错，请填写正
确的序号
warning: 该文件 "C:\Users\Dragon1573\Repos\Study-Notes\docs\02.数据可视化\01.Plotly\02.统计学图表\assets" 序号出错，请填写
正确的序号
tip add sidebar data. 侧边栏数据成功生成。
tip Apply theme vuepress-theme-vdoing ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin one-click-copy (i.e. "vuepress-plugin-one-click-copy") ...
tip Apply plugin zooming (i.e. "vuepress-plugin-zooming") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin sitemap (i.e. "vuepress-plugin-sitemap") ...
error @vuepress/internal-site-config apply extendMarkdown failed.
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Dragon1573\Repos\Study-Notes\node_modules\markdown-it-mathjax3\index.js from C:\Users\Dragon1573\Repos\Study-Notes\docs\.vuepress\config.js not supported.
Instead change the require of index.js in C:\Users\Dragon1573\Repos\Study-Notes\docs\.vuepress\config.js to a dynamic import() which is available in all CommonJS modules.
    at extendMarkdown (C:\Users\Dragon1573\Repos\Study-Notes\docs\.vuepress\config.js:27:12)
    at Option.syncApply (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\plugin-api\abstract\Option.js:110:15)
    at PluginAPI.applySyncOption (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\plugin-api\index.js:262:26)
    at afterInstantiate (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\createMarkdown.js:24:19)
    at module.exports (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\markdown\index.js:125:23)
    at module.exports (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\createMarkdown.js:27:10)    at App.process (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\App.js:113:21)
    at async dev (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\index.js:17:3)
```

</details>
<details>
<summary>Unexpected behavior when <code>yarn build</code></summary>

```text
C:\Users\Dragon1573\Repos\Study-Notes>yarn build   
wait Extracting site metadata...
warning: 该文件 "C:\Users\Dragon1573\Repos\Study-Notes\docs\01.机器学习\01.蓝桥云课\assets" 序号出错，请填写正确的序号
warning: 该文件 "C:\Users\Dragon1573\Repos\Study-Notes\docs\02.数据可视化\01.Plotly\01.基础图表\assets" 序号出错，请填写正
确的序号
warning: 该文件 "C:\Users\Dragon1573\Repos\Study-Notes\docs\02.数据可视化\01.Plotly\02.统计学图表\assets" 序号出错，请填写
正确的序号
tip add sidebar data. 侧边栏数据成功生成。
tip Apply theme vuepress-theme-vdoing ... 
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin one-click-copy (i.e. "vuepress-plugin-one-click-copy") ...       
tip Apply plugin zooming (i.e. "vuepress-plugin-zooming") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin sitemap (i.e. "vuepress-plugin-sitemap") ...
error @vuepress/internal-site-config apply extendMarkdown failed.
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Dragon1573\Repos\Study-Notes\node_modules\markdown-it-mathjax3\index.js from C:\Users\Dragon1573\Repos\Study-Notes\docs\.vuepress\config.js not supported.
Instead change the require of index.js in C:\Users\Dragon1573\Repos\Study-Notes\docs\.vuepress\config.js to a dynamic import() which is available in all CommonJS modules.
    at extendMarkdown (C:\Users\Dragon1573\Repos\Study-Notes\docs\.vuepress\config.js:27:12)
    at Option.syncApply (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\plugin-api\abstract\Option.js:110:15)
    at PluginAPI.applySyncOption (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\plugin-api\index.js:262:26)
    at afterInstantiate (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\createMarkdown.js:24:19)
    at module.exports (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\markdown\index.js:125:23)
    at module.exports (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\createMarkdown.js:27:10)    at App.process (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\node\App.js:113:21)
    at async build (C:\Users\Dragon1573\Repos\Study-Notes\node_modules\@vuepress\core\lib\index.js:26:3)
```

</details>

Could you please do me a favour again? Thank you very much!

**Comment by tani** [comment]
Thank you for the sharing issue. Let me explain why it has occurred.

- To fix #52, we added a new dependency juice in v3.0.0-0
- The package is available in node (SSG or SSR) except browsers (CSR) because juice has a dependency for node-native packages like `fs`
- For better compatibility including browsers, we replace juice by rehype-inline-css written by me.
- rehype-inline-css depends on the unifiedjs framework which is only for the ESM module, which makes errors in commonjs environment.
- Vuepress and Nuxt v3 might be stuck because they can only run on a legacy module system.

Therefore, we need to develop a new CSS inlining system to fix this system to run on the legacy module system without unifiedjs framework as a replacement of juice and rehype-inline-css .

**Comment by tani** [comment]
You can downgrade to v3.0.0-0 which uses the juice if you use this library only for the legacy system at the moment. 

Please wait for v3.1.0, I do my best to support es modules and commonjs modules

**Comment by Dragon1573** [comment]
Now I get it. Thank you @tani for your useful and powerful Markdown-it extension ❤️

I have introduced this package to several users on Bilibili platform (one of the largest video sharing platform in China, similar to YouTube). Most of them are new to GitHub and using Simplified Chinese asking for your help, which might bother you. I apology for that. 

Could you please pin this issue in the Issue List so other users can quickly notice it and avoid asking this same question again and again? Thank you! ❤️

**Comment by tani** [comment]
Now we do not need to pin this issue 😉 because I have built v3.1.1 without node-native package and with juice (`juice/client.js`). Hopefully, it must run on both platforms, node and browsers.

Please upgrade the package to v3.1.1. Cheers 🍻 

P.S. I am glad to hear that you introduce this plugin to the Chinese community. Thank you.
(I had an account in BiliBili but I was banned because I use the Japanese phone number to register. 🤣 )
Anyway, I do not mind receiving the questions in Chinese. Thanks, friend.

**Comment by tani** [comment]
Perfect. It's the expected behavior.
